pull_request_rules:
  - name: auto merge bump
    conditions:
      - and:
          - title~=^Bump [0-9]{8}-[0-9]+
          - author=lonerOrz
          - label=auto_bump
          - label=github_actions
          - check-success=flake check
          - check-success=All Garnix checks
    actions:
      update:
      merge:
        method: rebase

  - name: auto merge self pr
    conditions:
      - and:
          - author=lonerOrz
          - label=loner_pr
          - label=build-pr-success
          - check-success=flake check
          - check-success=All Garnix checks
    actions:
      merge:
        method: rebase

merge_protections_settings:
  reporting_method: check-runs
