name: Bump flakes

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      include_vendors_bump:
        description: "Include vendors bump"
        type: boolean
        default: true
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: flakes-bump
  cancel-in-progress: true

jobs:
  flakes-bump:
    name: Bump flakes
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      # identical to build.yml
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            accept-flake-config = true
            system-features = big-parallel gccarch-x86-64-v3
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      # config to commit
      - name: Bat-signal
        run: |
          set -e
          git config --global user.name 'Chaotic Github Actions'
          git config --global user.email 'actions@chaotic.cx'
      # based on group-bump.yml
      - name: Update, Rebase & PR
        run: |
          set -euo pipefail

          BRANCH_NAME="bump/flakes"
          DATE=$(date +%Y%m%d)

          git checkout -b "$BRANCH_NAME"

          OLD_COMMIT=$(git rev-parse HEAD)

          for f in 'nixpkgs' 'home-manager'; do
            PREV_MODIFIED="$(jq ".nodes.\"$f\".locked.lastModified" flake.lock)"

            nix flake update "$f"

            NEW_MODIFIED="$(jq ".nodes.\"$f\".locked.lastModified" flake.lock)"

            git add -A
            git commit -m "flakes/$f: $PREV_MODIFIED -> $NEW_MODIFIED" || echo 'Skipping commit'
          done

          if [[ "${INCLUDE_VENDORS:-true}" == "true" ]]; then
            vendor/update.sh
          else
            echo "Skipping vendors bump."
          fi

          # Check if a push is really necessary
          maintenance/scripts/remote-eq.sh "$BRANCH_NAME" "$OLD_COMMIT" || status=$?
          case ${status:-0} in
            0) ;;
            42) exit 0 ;;
            *) exit $conflict ;;
          esac

          # Force push to the branch
          git push origin "$BRANCH_NAME" --force

          # Check if the PR is already open
          PR_EXISTS=$(gh pr list --head "$BRANCH_NAME" --state open --json number | jq length)

          # Create the PR and trigger the merge queue
          if [ "$PR_EXISTS" -eq 0 ]; then
            echo "Creating a new PR"
            gh pr create \
              --title "chore: bump flakes" \
              --body "Automated flakes bump." \
              --head "$BRANCH_NAME" \
              --base main
          else
            echo "PR already exists. It has now been cleanly rebased and updated!"
          fi

          # Trigger auto-merge for the PR using a standard merge commit
          GH_TOKEN="$GH_CI_TOKEN" gh pr merge "$BRANCH_NAME" --auto --rebase
        env:
          GH_TOKEN: ${{ secrets.PAT_CHAOTIC }}
          GH_CI_TOKEN: ${{ github.token }}
          INCLUDE_VENDORS: ${{ inputs.include_vendors_bump }}
