name: Unpin
on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"

jobs:
  pin-kill:
    name: Unpin orphans
    runs-on: nyxbuilder
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            accept-flake-config = true
            sandbox-fallback = false
            system-features = big-parallel gccarch-x86-64-v3 kvm
          install_options: --daemon
      # similar to build.yml
      - name: Create niks3 auth-token
        run: |
          export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
          mkdir -p "$XDG_CONFIG_HOME"/niks3/
          printf "%s" "$NIKS3_TOKEN" > "$XDG_CONFIG_HOME"/niks3/auth-token
          wc "$XDG_CONFIG_HOME"/niks3/auth-token
        env:
          NIKS3_TOKEN: ${{ secrets.NIKS3_TOKEN }}
      - name: Diff and save
        run: bash ../../maintenance/scripts/clear-pins.sh
